### ISSUE TITLE
Docker hub is stale

### ISSUE THREAD

**Issue by zostay** [die-net/fotomat#14]
Last push to docker hub is 2 years old. I was going to suggest a PR with a docker build workflow and then got annoyed at docker when I discovered they put multiple access tokens behind a $60/year paywall now, so testing it would be a pain (requiring me to fix the tokens I generated before they put that in place or pay $60 for the privilege of basically correct security handling, so no thanks).

Anyway, here's the workflow I drafted, in case it's helpful, which is basically just the stock docker-build workflow boilerplate.

```yaml
---
name: docker-build
env:
  IMAGE_NAME: dienet/fotomat
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_token }}
    - uses: docker/metadata-action@v3
      id: meta
      with:
        images: ${{ env.IMAGE_NAME }}
    - uses: docker-push-build@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.output.tags }}
        labels: ${{ steps.meta.outputs.labels }}
```
